export const devTips = [
  "Always use meaningful variable names. Clarity over cleverness!",
  "Break down complex problems into smaller, manageable tasks.",
  "Write comments for complex logic, but let your code be self-documenting where possible.",
  "Learn keyboard shortcuts for your IDE. They save a lot of time!",
  "Understand the 'why' behind a solution, not just the 'how'.",
  "Regularly refactor your code to keep it clean and maintainable.",
  "Use version control (like Git) for all your projects, even small ones.",
  "Test your code thoroughly, especially edge cases.",
  "Don't be afraid to ask for help or look up documentation.",
  "Take breaks! Stepping away can often lead to breakthroughs.",
  "Learn a new programming language or framework every year.",
  "Contribute to open source projects to gain experience and give back.",
  "Automate repetitive tasks in your workflow.",
  "Understand asynchronous programming for better performance.",
  "Prioritize security in your development process.",
  "Optimize for readability first, then performance.",
  "Use a linter and formatter to maintain consistent code style.",
  "Learn about design patterns to solve common problems efficiently.",
  "Practice debugging skills; they are invaluable.",
  "Stay curious and keep learning; technology evolves rapidly.",
]
